### ISSUE TITLE
Unable to authenticate and fetch eight token

### ISSUE THREAD

**Issue by sferguson524** [mezz64/pyEight#9]
Been seeing Unable to authenticate and fetch eight token for the last few days.  Also seeign 404s in the Home assistant logs when posting eight data.  Usernames and passwords have not changed.

**Comment by mezz64** [comment]
The API url changed. It has already been fixed in the latest release and merged into Hass Dev branch.

**Comment by sferguson524** [comment]
Just did a pip install --upgrade to the latest version in my lab, and am
still seeing the issue

**Comment by mezz64** [comment]
Make sure you are actually on 0.1.2.  If you enable debug logging it will print out the version during startup.  I just tested again and all is working fine as far as i can tell.
